apiVersion: v2
name: cf-switch
description: A Helm chart for CF-Switch - Cloudflare WAF Custom Rule toggle service
type: application
version: 0.8.0
appVersion: 0.8.0
keywords:
  - cloudflare
  - waf
  - security
  - toggle
home: https://github.com/meyeringh/cf-switch
sources:
  - https://github.com/meyeringh/cf-switch
maintainers:
  - name: meyeringh
    url: https://github.com/meyeringh
